### ISSUE TITLE
D12 Zenner diode draws too much current

### ISSUE THREAD

**Issue by maciejprzybysz** [sinara-hw/Thermostat#92]
During thermal tests of the Thermostat, we noticed that the 1SMA5914BT3G Zenner diode (D12) gets warm. The photo from the thermal imaging camera also shows that significant amount of power is emitted on the R35 resistor.
![FLIR2399](https://user-images.githubusercontent.com/48446953/106623935-69784200-6575-11eb-8c7c-5bd153930c9b.jpg)

Measurement with a multimeter shows that, depending on the device (several pieces checked), the R35 resistor drops voltage to ~ 3.15-3.30V. The same voltage was measured at diode D12.
![2021-02-02_16h14_48](https://user-images.githubusercontent.com/48446953/106623401-db9c5700-6574-11eb-8def-ad90090e0451.png)

After desoldering the diode and examining it, it turned out that at 3.15V the diode current is over 50mA. In the [datasheet](https://pl.mouser.com/datasheet/2/308/1SMA5913BT3_D-1101349.pdf) you can find this specification:
![2021-02-02_16h17_08](https://user-images.githubusercontent.com/48446953/106623362-d3441c00-6574-11eb-811b-d4abdee79e44.png)

This Zenner should be changed to a more suitable one. The absolute maximum rating on the AD7172 inputs is 3.3V+0.3V so Vz(max)<3.6V and current at 3V3 should be much less than 50mA. I checked distributors stock and didn't find such diode in SMA case (same as 1SMA5914BT3G), so we ordered this one for testing:
[PLZ3V3B-G3-H](https://pl.mouser.com/ProductDetail/Vishay-Semiconductors/PLZ3V3B-G3-H?qs=ECv811tYSNiXaJv05vovrQ%3D%3D)

It should be solderable on existing boards, but changing footprint in the next review should be considered.

**Comment by gkasprow** [comment]
This issue was fixed [ already ](https://github.com/sinara-hw/Thermostat/issues/48)

**Comment by maciejprzybysz** [comment]
> This issue was fixed [ already ](https://github.com/sinara-hw/Thermostat/issues/48)

Ok, I had to miss this issue. This change is not pushed on latest commit nor is it listed on [v2.2 changes issue](https://github.com/sinara-hw/Thermostat/issues/84), so I thought there was still a problem.

**Comment by gkasprow** [comment]
This is still a work in progress

**Comment by gkasprow** [comment]
I pushed all the recent changes

**Comment by gkasprow** [comment]
fixed
